[theme]

# Primary accent color for interactive elements
primaryColor = "#d33682"

# Background color for the main content area
backgroundColor = "#002b36"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#657b83"

# Color used for almost all text
textColor = "#dfe"

[client]
toolbarMode = "minimal"
